# Exercise 1.A NumPy: Manipulating Arrays

In [28]:
import numpy as np

In [29]:
## Looping Through Arrays

In [61]:
arrA = np.array([
    [11, 12, 13,],
    [14, 15, 16,]
    ])

print(arrA)

[[11 12 13]
 [14 15 16]]


In [31]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [32]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The key difference between these two results are the different dimensions.  
In the first result, we are only looping through the first dimension, aka the rows kind of like:  
2*(11, 12, 13)
2*(14, 15, 16)
 The second result is going through the second dimension, the individual values within the rows, which is like:  
2*(11),  
2*(12),  
2*(13)...

In [62]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)

# This result is different because loop_result is representing the entire row, so when you *2, the row is printed repeatedly.

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [ ]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0) #if left empty,axis=0 is the default value

print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [43]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)

print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [56]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1)) #axis=0

print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [ ]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))

#ValueError error, this is due to the arrays im trying to stack together having a different shape.

ValueError: all input arrays must have the same shape

In [47]:
another_joined_array = np.concatenate((joined_array_1, arrA))

print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [ ]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)

#Changing the axis gives the another ValueError due to the rows now having different dimensions with added axis=1

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [ ]:
testh = np.hstack((arrA, arrA))
testv = np.vstack((arrA, arrA))
testd = np.dstack((arrA, arrA))

print(testh)
# the h in hstack means horizontal(probably), so the arrays are being stacked horizontally rather than vertically
print(testv)
# the v in vstack means horizontal(probably), so the arrays are being stacked vertically, however unlike a regular stack() it does not create a new dimension and puts them in a single dimension
print(testd)
# the d in dstack means depth(again probably), will ask Bess I'm not sure what this means or does

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [72]:
splitsky = np.array_split(joined_array_1, 2)

print(splitsky)

# There are now 2 arrays, and each array has two dimensions

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [ ]:
splitterino = np.array_split(joined_array_1, 3)

print(splitterino)

#There are now 3 arrays each with still two dimensions


[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [83]:
result_1 = np.where(arrA % 2 == 0, 'arrA', 'odd')

print(result_1)

# np.where(array conditional , array value to print if conditions are met, "else" what to print if condition is not met)

[['odd' 'arrA' 'odd']
 ['arrA' 'odd' 'arrA']]


## Sorting and Filtering Arrays

In [88]:
arrB = np.array([
    [7, 6],
    [13, 5],
    [7, 3]
    ])

arrB_sorted = np.sort(arrB)

print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [89]:
print(arrB)

[[ 7  6]
 [13  5]
 [ 7  3]]


In [ ]:
z = arrB < 7
print(z)

arrC = arrB[z] #Takes only values where Z is true
print(arrC)

[[False  True]
 [False  True]
 [False  True]]
[6 5 3]


In [96]:
y = arrB >=7

arrD = arrB[y]

print(y)

[[ True False]
 [ True False]
 [ True False]]
