Exercise 1.B NumPy Random

In [17]:
import numpy as np

##

## Generating Random Numbers

In [18]:
r_1 = np.random.randint(1, 20, size=(2))

print(r_1)

[10 15]


In [19]:
r_2 = np.random.randint(1, 20, size=(1, 2))

print(r_2)

[[13 19]]


In [20]:
r_3 = np.random.rand(2, 1)

print(r_3)

[[4.86337378e-04]
 [6.63303645e-01]]


In [21]:
r_4 = np.random.randint(20, 100, size=(4, 5))

print(r_4)

[[26 24 97 81 49]
 [56 63 27 47 25]
 [47 99 49 57 76]
 [51 29 24 71 89]]


In [22]:
r_5 = np.random.rand(4, 5)

print(r_5)

[[0.18804365 0.31121406 0.44295076 0.82431583 0.25247645]
 [0.86607956 0.00722774 0.56129096 0.15139199 0.0015777 ]
 [0.20095151 0.14254048 0.41748766 0.74633725 0.89694975]
 [0.69379829 0.44468273 0.5431474  0.05561713 0.66355516]]


## Generating Random Choices from an Array

In [ ]:
students = np.array([
    'Bess',
    'Nigel',
    'Brandon',
    'Kevin',
    'Sthefanie',
    'Jeremiah',
    'Hritik',
    'Luis',
    'Dahlia',
    'Destiney',
    'Natalia',
    'Edmund'
])

In [24]:
call_on = np.random.choice(students)

print(call_on)

Nigel


In [ ]:
breakout_groups = np.random.choice(
    students,
    size=(3, 4)
    # , replace=False # <------------ would make no duplicates
)

print(breakout_groups)

# This would not be an effective way to generate breakout groups as there are duplicates and missing names, adding replace=False would make it good for breakout roomsto aboid this.

[['Jeremiah' 'Hritik' 'Luis' 'Edmund']
 ['Nigel' 'Dahlia' 'Natalia' 'Bess']
 ['Sthefanie' 'Destiney' 'Brandon' 'Kevin']]


In [42]:
call_on_weighted = np.random.choice(
    students, 
    size=5,
    p=[0, 0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.05, 0.05, 0.05, 0.05, 0.3],
)

print(call_on_weighted)

# I gave Bess and Nigel 0s as they are instructors and have no chance of getting called on. 
# The rest of the students I just gave random values that add to 1 with me having 0.3, the highest chance to be called.

['Nigel' 'Hritik' 'Nigel' 'Nigel' 'Jeremiah']


## Generating a Normal Distribution

In [45]:
bell_curve = np.random.normal(
    loc=10,     # mean
    scale=5,    # standard deviation
    size=(4,5)  # rows/columns
)

print(bell_curve)

[[ 3.80291432  8.54850132 19.18546105  9.95966217 10.80797736]
 [14.06245541  6.13057298 14.84754268 24.42008186 14.26289119]
 [12.01972159  8.97194478  5.87610798  3.69644241  9.78004618]
 [11.5091557   4.62017465  9.06355993 13.1753569   8.1426587 ]]
