# Exercise 1.C Performing Operations on Arrays

In [1]:
import numpy as np

## Sample Arrays

In [14]:
r_1 = np.random.randint(1, 20, size=(2))
print(f'r_1: \n {r_1}')

r_2 = np.random.randint(1, 20, size=(1, 2))
print(f'r_2: \n {r_2}')

r_3 = np.random.rand(2, 1)
print(f'r_3: \n {r_3}')

r_4 = np.random.randint(20, 100, size=(4, 5))
print(f'r_4: \n {r_4}')

r_1: 
 [4 6]
r_2: 
 [[10 11]]
r_3: 
 [[0.40263308]
 [0.10005659]]
r_4: 
 [[41 41 54 50 92]
 [77 53 62 81 96]
 [54 77 98 21 25]
 [66 88 62 72 90]]


## Permutations

In [15]:
print(r_4)

[[41 41 54 50 92]
 [77 53 62 81 96]
 [54 77 98 21 25]
 [66 88 62 72 90]]


In [37]:
np.random.shuffle(r_4)

print(r_4)

[[66 88 62 72 90]
 [41 41 54 50 92]
 [54 77 98 21 25]
 [77 53 62 81 96]]


The elements in the array were shuffled as whole rows. The entire rows shuffled but not the values within them.

In [26]:
new_shuffle = np.random.permutation(r_4)

print(new_shuffle)
print('\n')
print(r_4)

[[41 41 54 50 92]
 [77 53 62 81 96]
 [54 77 98 21 25]
 [66 88 62 72 90]]


[[66 88 62 72 90]
 [54 77 98 21 25]
 [41 41 54 50 92]
 [77 53 62 81 96]]


Shuffle randomizes the currenty array, while permutation creates a new one in a random order.  
    Shuffle is useful if you will be working with the same array  
    while permutation is useful to create multiple new randomized arrays.

## Mathematical Operations

In [54]:
print('r_1 and r_2:')
print(r_1)
print(r_2)

print('\n shapes:')
print(r_1.shape)
print(r_2.shape)

print('\n r_1 and r_2 added together plus shape:')
print(np.add(r_1, r_2))
print(np.add(r_1, r_2).shape)

r_1 and r_2:
[4 6]
[[10 11]]

 shapes:
(2,)
(1, 2)

 r_1 and r_2 added together plus shape:
[[14 17]]
(1, 2)


In [56]:
print('r_1 and r_3:')
print(f'{r_1}\n{r_3}')

print('\n shapes:')
print(f'{r_1.shape}\n{r_3.shape}')

print('\n r_1 and r_3 added together plus shape:')
print(np.add(r_1, r_3))
print(np.add(r_1, r_3).shape)

r_1 and r_3:
[4 6]
[[0.40263308]
 [0.10005659]]

 shapes:
(2,)
(2, 1)

 r_1 and r_3 added together plus shape:
[[4.40263308 6.40263308]
 [4.10005659 6.10005659]]
(2, 2)


In [66]:
print('r_2 and r_4:')
print(f'{r_2}\n{r_4}')

print('\n shapes:')
print(f'{r_2.shape}\n{r_4.shape}')

print('\n r_2 and r_4 added together plus shape:') # See code below for explanation of error
print(np.add(r_2, r_4))
print(np.add(r_2, r_4).shape)

r_2 and r_4:
[[10 11]]
[[66 88 62 72 90]
 [41 41 54 50 92]
 [54 77 98 21 25]
 [77 53 62 81 96]]

 shapes:
(1, 2)
(4, 5)

 r_2 and r_4 added together plus shape:


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [70]:
np.add(r_1, r_4)

#Adding r_1, r_2, or r_3 with r_4 returns a value error as they have incompatible shapes with r_4
#Arrays need to have the columns be EQUAL or one of them = 1 AND the amount of rows must be EQUAL or one of them =1

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [67]:
np.add(np.array([1]), r_4)

array([[67, 89, 63, 73, 91],
       [42, 42, 55, 51, 93],
       [55, 78, 99, 22, 26],
       [78, 54, 63, 82, 97]])

In [68]:
np.add(np.array([[1]]), r_4)

array([[67, 89, 63, 73, 91],
       [42, 42, 55, 51, 93],
       [55, 78, 99, 22, 26],
       [78, 54, 63, 82, 97]])

In [69]:
np.add(np.array([1,1,1,1,1]), r_4)

array([[67, 89, 63, 73, 91],
       [42, 42, 55, 51, 93],
       [55, 78, 99, 22, 26],
       [78, 54, 63, 82, 97]])

In [71]:
np.add(np.array([1],[1]), r_4)

TypeError: Field elements must be 2- or 3-tuples, got '1'

The values are added left to right and are contained by the following rules for columns and rows:  
- Columns - The columns must be equal or one of them is 1  
- Rows - The row must be equal or one of them is 1
- These must both be true to be able to combine two arrays
- (these bullet points were on accident)

## Rounding