# Exercise 1.C Performing Operations on Arrays

In [2]:
import numpy as np

## Sample Arrays

In [3]:
r_1 = np.random.randint(1, 20, size=(2))
print(f'r_1: \n {r_1}')

r_2 = np.random.randint(1, 20, size=(1, 2))
print(f'r_2: \n {r_2}')

r_3 = np.random.rand(2, 1)
print(f'r_3: \n {r_3}')

r_4 = np.random.randint(20, 100, size=(4, 5))
print(f'r_4: \n {r_4}')

r_1: 
 [ 6 10]
r_2: 
 [[10 18]]
r_3: 
 [[0.13873872]
 [0.73079402]]
r_4: 
 [[58 45 99 20 20]
 [34 26 30 45 26]
 [52 69 53 29 31]
 [28 93 74 41 49]]


## Permutations

In [4]:
print(r_4)

[[58 45 99 20 20]
 [34 26 30 45 26]
 [52 69 53 29 31]
 [28 93 74 41 49]]


In [5]:
np.random.shuffle(r_4)

print(r_4)

[[28 93 74 41 49]
 [58 45 99 20 20]
 [34 26 30 45 26]
 [52 69 53 29 31]]


The elements in the array were shuffled as whole rows. The entire rows shuffled but not the values within them.

In [6]:
new_shuffle = np.random.permutation(r_4)

print(new_shuffle)
print('\n')
print(r_4)

[[34 26 30 45 26]
 [28 93 74 41 49]
 [52 69 53 29 31]
 [58 45 99 20 20]]


[[28 93 74 41 49]
 [58 45 99 20 20]
 [34 26 30 45 26]
 [52 69 53 29 31]]


Shuffle randomizes the currenty array, while permutation creates a new one in a random order.  
    Shuffle is useful if you will be working with the same array  
    while permutation is useful to create multiple new randomized arrays.

## Mathematical Operations

In [7]:
print('r_1 and r_2:')
print(r_1)
print(r_2)

print('\n shapes:')
print(r_1.shape)
print(r_2.shape)

print('\n r_1 and r_2 added together plus shape:')
print(np.add(r_1, r_2))
print(np.add(r_1, r_2).shape)

r_1 and r_2:
[ 6 10]
[[10 18]]

 shapes:
(2,)
(1, 2)

 r_1 and r_2 added together plus shape:
[[16 28]]
(1, 2)


In [8]:
print('r_1 and r_3:')
print(f'{r_1}\n{r_3}')

print('\n shapes:')
print(f'{r_1.shape}\n{r_3.shape}')

print('\n r_1 and r_3 added together plus shape:')
print(np.add(r_1, r_3))
print(np.add(r_1, r_3).shape)

r_1 and r_3:
[ 6 10]
[[0.13873872]
 [0.73079402]]

 shapes:
(2,)
(2, 1)

 r_1 and r_3 added together plus shape:
[[ 6.13873872 10.13873872]
 [ 6.73079402 10.73079402]]
(2, 2)


In [9]:
print('r_2 and r_4:')
print(f'{r_2}\n{r_4}')

print('\n shapes:')
print(f'{r_2.shape}\n{r_4.shape}')

print('\n r_2 and r_4 added together plus shape:') # See code below for explanation of error
print(np.add(r_2, r_4))
print(np.add(r_2, r_4).shape)

r_2 and r_4:
[[10 18]]
[[28 93 74 41 49]
 [58 45 99 20 20]
 [34 26 30 45 26]
 [52 69 53 29 31]]

 shapes:
(1, 2)
(4, 5)

 r_2 and r_4 added together plus shape:


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [ ]:
np.add(r_1, r_4)

#Adding r_1, r_2, or r_3 with r_4 returns a value error as they have incompatible shapes with r_4
#Arrays need to have the columns be EQUAL or one of them = 1 AND the amount of rows must be EQUAL or one of them =1

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

In [ ]:
np.add(np.array([1]), r_4)

array([[67, 89, 63, 73, 91],
       [42, 42, 55, 51, 93],
       [55, 78, 99, 22, 26],
       [78, 54, 63, 82, 97]])

In [ ]:
np.add(np.array([[1]]), r_4)

array([[67, 89, 63, 73, 91],
       [42, 42, 55, 51, 93],
       [55, 78, 99, 22, 26],
       [78, 54, 63, 82, 97]])

In [ ]:
np.add(np.array([1,1,1,1,1]), r_4)

array([[67, 89, 63, 73, 91],
       [42, 42, 55, 51, 93],
       [55, 78, 99, 22, 26],
       [78, 54, 63, 82, 97]])

In [ ]:
np.add(np.array([1],[1]), r_4)

TypeError: Field elements must be 2- or 3-tuples, got '1'

The values are added left to right and are contained by the following rules for columns and rows:  
- Columns - The columns must be equal or one of them is 1  
- Rows - The row must be equal or one of them is 1
- These must both be true to be able to combine two arrays
- (these bullet points were on accident)

## Rounding

In [10]:
print(r_3)

[[0.13873872]
 [0.73079402]]


In [ ]:
print(np.trunc(r_3)) #trunc chops off decimals, bascially rounds down

[[0.]
 [0.]]


In [ ]:
print(np.fix(r_3)) # fix rounds to nearest integer towards zero

[[0.]
 [0.]]


In [ ]:
print(np.floor(r_3)) # floor rounds down

[[0.]
 [0.]]


In [ ]:
print(np.ceil(r_3)) # ceil rounds up

[[1.]
 [1.]]


In [17]:
print(np.round(r_3, 2))

[[0.14]
 [0.73]]


## Cumulative Operations

In [18]:
print(r_4)

[[28 93 74 41 49]
 [58 45 99 20 20]
 [34 26 30 45 26]
 [52 69 53 29 31]]


In [19]:
print(np.sum(r_4))

922


In [20]:
print(np.sum(r_4, axis=0))

[172 233 256 135 126]


In [21]:
print(np.sum(r_4, axis=1))

[285 242 161 234]


In [22]:
print(np.cumsum(r_4))

[ 28 121 195 236 285 343 388 487 507 527 561 587 617 662 688 740 809 862
 891 922]


In [27]:
print(np.cumsum(r_4, axis=0))
print('\n')
print(np.cumsum(r_4, axis=1))

[[ 28  93  74  41  49]
 [ 86 138 173  61  69]
 [120 164 203 106  95]
 [172 233 256 135 126]]


[[ 28 121 195 236 285]
 [ 58 103 202 222 242]
 [ 34  60  90 135 161]
 [ 52 121 174 203 234]]


## Grocery Problem

In [35]:
#arrays are ordered as vegetables, fruits, boxes of snacks, beverages
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [36]:
print(f'The first bag contains {np.sum(bag1)} items, and the second bag contains {np.sum(bag2)} items.')

The first bag contains 9 items, and the second bag contains 7 items.


In [37]:
bagsum = bag1 + bag2

print(f'There are {bagsum[0]} vegetables, {bagsum[1]} fruits, {bagsum[2]} boxes of snacks, and {bagsum[3]} beverages in the two grocery bags')

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags


## Teamwork

In [38]:
#values are ordered as: mon, tue, wed, thur, fri
Ali = np.array([5, 4, 6, 4, 2])

In [39]:
Ben = np.array([0, 5, 5, 3, 4])

In [40]:
Carla = np.array([3, 6, 0, 3, 4])

In [43]:
all_knocks = np.array([
    Ali,
    Ben,
    Carla
])

print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [ ]:
#Ali 21, Ben 17, Carla 16
print(np.sum(all_knocks, axis=1))

#sum of all doors knocked on = 54
print(np.sum(all_knocks))

[21 17 16]
54


In [60]:
#sum of all knocks for each day, turns the 3 rows into 1
daily_knocks = np.sum(all_knocks, axis=0)

#find cumulative sum of each day, and multiply by 0.5 to convert the knocks into votes
cum_votes= np.cumsum((daily_knocks * 0.5))
print(f'Rolling total of votes for each day:\n{cum_votes}')



Rolling total of votes for each day:
[ 4.  11.5 17.  22.  27. ]
